---
- name: Configure disk
  ansible.builtin.include_tasks: disk.yml

- name: Configure NIC
  ansible.builtin.include_tasks: nic.yml

- name: Update VM configuration
  community.general.proxmox_kvm:
    acpi: "{{ pve_acpi | default(omit) }}"
    agent: "{{ pve_agent | default(omit) }}"
    args: "{{ pve_args | default(omit) }}"
    autostart: "{{ pve_autostart | default(omit) }}" # currently ignored in API
    balloon: "{{ pve_balloon | default(omit) }}"
    bios: "{{ pve_bios | default(omit) }}"
    boot: "{{ pve_boot | default(omit) }}"
    bootdisk: "{{ pve_bootdisk | default(omit) }}"
    cicustom: "{{ pve_cicustom | default(omit) }}"
    cipassword: "{{ pve_cipassword | default(omit) }}"
    citype: "{{ pve_citype | default(omit) }}"
    ciuser: "{{ pve_ciuser | default(omit) }}"
    cores: "{{ pve_cores | default(omit) }}"
    cpu: "{{ pve_cpu | default(omit) }}"
    cpulimit: "{{ pve_cpulimit | default(omit) }}"
    cpuunits: "{{ pve_cpuunits | default(omit) }}"
    delete: "{{ pve_delete | default(omit) }}"
    description: "{{ pve_description | default(omit) }}"
    digest: "{{ pve_digest | default(omit) }}"
    freeze: "{{ pve_freeze | default(omit) }}"
    hostpci: "{{ pve_hostpci | default(omit) }}"
    hotplug: "{{ pve_hotplug | default(omit) }}"
    hugepages: "{{ pve_hugepages | default(omit) }}"
    ipconfig: "{{ pve_ipconfig | default(omit) }}"
    keyboard: "{{ pve_keyboard | default(omit) }}"
    kvm: "{{ pve_kvm | default(omit) }}"
    localtime: "{{ pve_localtime | default(omit) }}"
    lock: "{{ pve_lock | default(omit) }}"
    machine: "{{ pve_machine | default(omit) }}"
    memory: "{{ pve_memory | default(omit) }}"
    migrate_downtime: "{{ pve_migrate_downtime | default(omit) }}"
    migrate_speed: "{{ pve_migrate_speed | default(omit) }}"
    name: "{{ pve_name }}"
    nameservers: "{{ pve_nameservers | default(omit) }}"
    node: "{{ pve_target }}"
    numa_enabled: "{{ pve_numa_enabled | default(omit) }}"
    numa: "{{ pve_numa | default(omit) }}"
    onboot: "{{ pve_onboot | default(omit) }}"
    ostype: "{{ pve_ostype | default(omit) }}"
    parallel: "{{ pve_parallel | default(omit) }}"
    pool: "{{ pve_pool | default(omit) }}"
    protection: "{{ pve_protection | default(omit) }}"
    scsihw: "{{ pve_scsihw | default(omit) }}"
    searchdomains: "{{ pve_searchdomains | default(omit) }}"
    serial: "{{ pve_serial | default(omit) }}"
    shares: "{{ pve_shares | default(omit) }}"
    skiplock: "{{ pve_skiplock | default(omit) }}"
    smbios: "{{ pve_smbios | default(omit) }}"
    sockets: "{{ pve_sockets | default(omit) }}"
    sshkeys: "{{ pve_sshkeys | default(omit) }}"
    startdate: "{{ pve_startdate | default(omit) }}"
    startup: "{{ pve_startup | default(omit) }}"
    tablet: "{{ pve_tablet | default(omit) }}"
    tags: "{{ pve_tags | default(omit) }}"
    tdf: "{{ pve_tdf | default(omit) }}"
    timeout: "{{ pve_timeout | default(omit) }}"
    update: true
    vcpus: "{{ pve_vcpus | default(omit) }}"
    vga: "{{ pve_vga | default(omit) }}"
    vmid: "{{ kvm_created.vmid }}"
    watchdog: "{{ pve_watchdog | default(omit) }}"
    state: present
  when: pve_update
  # NOTE: not idempotent, see https://github.com/ansible-collections/community.general/issues/1965
